__title__ = 'pubdns'
__description__ = 'Python library to interact with public DNS servers'
__url__ = 'https://github.com/mehrdadrad/pubdns'
__version__ = '0.1.2'
__author__ = 'Mehrdad Arshad Rad'
__author_email__ = 'arshad.rad@gmail.com'
__license__ = 'MIT'
